#! /usr/bin/env python
import cv2
import nodes.webCamVideo

if __name__ == '__main__':
    #nodes.webCamVideo.say('my friend!')
    vid = nodes.webCamVideo.getVideo()
    print vid
    
    print "Well Done Man ...."
